
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_POSE_TOKEN = "<pose>"
SPECICAL_POSE_TOKEN = "<POSE>"

IMAGE_PATCH_TOKEN = "<im_patch>"
IMG_START_TOKEN = "<img>"
IMG_END_TOKEN = "</img>"


IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
POSE_TOKEN_INDEX = -150


